MachineIntelligenceCore:NeuralNets: src/loss/LossTests.cpp File Reference
LossTests.cpp File Reference
#include "LossTests.hpp"
#include "LossTypes.hpp"
Functions
TEST_F (Vectors4x1Float, SquaredErrorLoss)
TEST_F (Vectors4x1Float, SquaredErrorMSELoss)
TEST_F (Vectors4x1Float, SquaredErrorGradient)
TEST_F (Vectors4x1Float2, SquaredErrorLoss)
TEST_F (Vectors4x1Float2, SquaredErrorMSELoss)
TEST_F (Vectors4x1Float2, SquaredErrorGradient)
TEST_F (Vectors4x1Float2, CrossEntropyLoss)
TEST_F (Vectors4x1Float2, CrossEntropyACELoss)
TEST_F (Vectors4x1Float2, CrossEntropyGradient)
TEST_F (Vectors3x2Float, SquaredErrorLoss)
TEST_F (Vectors3x2Float, SquaredErrorACELoss)
TEST_F (Vectors3x2Float, SquaredErrorGradient)
TEST_F (Vectors3x2Float, CrossEntropyLoss)
TEST_F (Vectors3x2Float, CrossEntropyACELoss)
TEST_F (Vectors3x2Float, CrossEntropyGradient)
int main (int argc, char **argv)
Detailed Description
Copyright (C) tkornuta, IBM Corporation 2015-2019
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
: Tomasz Kornuta tkorn.nosp@m.ut@u.nosp@m.s.ibm.nosp@m..com : Nov 9, 2016
Copyright (c) 2016, IBM Corporation. All rights reserved.
Definition in file LossTests.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 258 of file LossTests.cpp.
TEST_F (Vectors4x1Float , SquaredErrorLoss)
Tests squared error loss function on vector with four floats.
Definition at line 32 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateLoss().
TEST_F (Vectors4x1Float , SquaredErrorMSELoss)
Tests mean squared error (MSE) loss function on vector with four floats.
Definition at line 42 of file LossTests.cpp.
References mic::neural_nets::loss::Loss< dtype >::calculateMeanLoss().
TEST_F (Vectors4x1Float , SquaredErrorGradient)
Tests squared error loss function on vectors with four elements.
Definition at line 52 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateGradient().
TEST_F (Vectors4x1Float2 , SquaredErrorLoss)
Tests squared error loss function on 2 different predicted vectors with four floats.
Definition at line 65 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateLoss().
TEST_F (Vectors4x1Float2 , SquaredErrorMSELoss)
Tests mean squared error loss function on 2 different predicted vectors with four floats.
Definition at line 80 of file LossTests.cpp.
References mic::neural_nets::loss::Loss< dtype >::calculateMeanLoss().
TEST_F (Vectors4x1Float2 , SquaredErrorGradient)
Tests squared error gradient on 2 different predicted vectors with four elements.
Definition at line 95 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateGradient().
TEST_F (Vectors4x1Float2 , CrossEntropyLoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 118 of file LossTests.cpp.
References mic::neural_nets::loss::CrossEntropyLoss< dtype >::calculateLoss().
TEST_F (Vectors4x1Float2 , CrossEntropyACELoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 133 of file LossTests.cpp.
References mic::neural_nets::loss::Loss< dtype >::calculateMeanLoss().
TEST_F (Vectors4x1Float2 , CrossEntropyGradient)
Tests cross-entropy gradient on 2 different predicted vectors with four elements.
Definition at line 149 of file LossTests.cpp.
References mic::neural_nets::loss::CrossEntropyLoss< dtype >::calculateGradient().
TEST_F (Vectors3x2Float , SquaredErrorLoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 171 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateLoss().
TEST_F (Vectors3x2Float , SquaredErrorACELoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 183 of file LossTests.cpp.
References mic::neural_nets::loss::Loss< dtype >::calculateMeanLoss().
TEST_F (Vectors3x2Float , SquaredErrorGradient)
Tests squared error loss function on vectors with four elements.
Definition at line 196 of file LossTests.cpp.
References mic::neural_nets::loss::SquaredErrorLoss< dtype >::calculateGradient().
TEST_F (Vectors3x2Float , CrossEntropyLoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 216 of file LossTests.cpp.
References mic::neural_nets::loss::CrossEntropyLoss< dtype >::calculateLoss().
TEST_F (Vectors3x2Float , CrossEntropyACELoss)
Tests cross-entropy loss function on 2 different predicted vectors with four floats.
Definition at line 229 of file LossTests.cpp.
References mic::neural_nets::loss::Loss< dtype >::calculateMeanLoss().
TEST_F (Vectors3x2Float , CrossEntropyGradient)
Tests squared error loss function on vectors with four elements.
Definition at line 241 of file LossTests.cpp.
References mic::neural_nets::loss::CrossEntropyLoss< dtype >::calculateGradient().