MachineIntelligenceCore:NeuralNets: mic::neural_nets::unit_tests::Simple2LayerRegressionNN Class Reference
mic::neural_nets::unit_tests::Simple2LayerRegressionNN Class Reference
Test Fixture - simple ff net with 2 layers.
#include <MultiLayerNeuralNetworkTests.hpp>
Public Member Functions
Simple2LayerRegressionNN ()
Protected Member Functions
virtual void SetUp ()
Private Attributes
mic::mlnn::BackpropagationNeuralNetwork
< double > nn
Detailed Description
Test Fixture - simple ff net with 2 layers.
Author
tkornuta
Definition at line 44 of file MultiLayerNeuralNetworkTests.hpp.
Constructor & Destructor Documentation
mic::neural_nets::unit_tests::Simple2LayerRegressionNN::Simple2LayerRegressionNN () inline
Definition at line 47 of file MultiLayerNeuralNetworkTests.hpp.
References nn, mic::mlnn::MultiLayerNeuralNetwork< eT >::pushLayer(), and mic::mlnn::BackpropagationNeuralNetwork< eT >::setLoss().
Member Function Documentation
virtual void mic::neural_nets::unit_tests::Simple2LayerRegressionNN::SetUp () inline protected virtual
Definition at line 59 of file MultiLayerNeuralNetworkTests.hpp.
References nn, mic::mlnn::MultiLayerNeuralNetwork< eT >::resetGrads(), and mic::mlnn::MultiLayerNeuralNetwork< eT >::resizeBatch().
Member Data Documentation
mic::mlnn::BackpropagationNeuralNetwork<double> mic::neural_nets::unit_tests::Simple2LayerRegressionNN::nn private
Definition at line 68 of file MultiLayerNeuralNetworkTests.hpp.
Referenced by SetUp(), and Simple2LayerRegressionNN().
The documentation for this class was generated from the following file:
src/mlnn/MultiLayerNeuralNetworkTests.hpp