MachineIntelligenceCore:NeuralNets: src/optimization/AdaDeltaTests.cpp File Reference
AdaDeltaTests.cpp File Reference
#include <gtest/gtest.h>
#include <cmath>
#include <optimization/ArtificialLandscapesTests.hpp>
#include <optimization/AdaDelta.hpp>
Macros
#define private public
Functions
TEST_F (Sphere1DLandscape, AdaDelta_Convergence)
TEST_F (Sphere20DLandscape, AdaDelta_Convergence)
TEST_F (Beale2DLandscape, DISABLED_AdaDelta_Convergence)
Detailed Description
Copyright (C) tkornuta, IBM Corporation 2015-2019
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
: Tomasz Kornuta tkorn.nosp@m.ut@u.nosp@m.s.ibm.nosp@m..com : Nov 18, 2016
Copyright (c) 2016, IBM Corporation. All rights reserved.
Definition in file AdaDeltaTests.cpp.
Macro Definition Documentation
#define private public
Definition at line 31 of file AdaDeltaTests.cpp.
Function Documentation
TEST_F (Sphere1DLandscape , AdaDelta_Convergence)
Tests AdaDelta on a 1d square "artificial landscape".
Author
tkornuta
Definition at line 44 of file AdaDeltaTests.cpp.
References mic::neural_nets::optimization::OptimizationFunction< eT >::update().
TEST_F (Sphere20DLandscape , AdaDelta_Convergence)
Tests AdaDelta on a 20d square "artificial landscape".
Author
tkornuta
Definition at line 73 of file AdaDeltaTests.cpp.
References mic::neural_nets::optimization::OptimizationFunction< eT >::update().
TEST_F (Beale2DLandscape , DISABLED_AdaDelta_Convergence)
Tests AdaDelta on a 2d Beale's function "artificial landscape".
Author
tkornuta
Definition at line 102 of file AdaDeltaTests.cpp.
References mic::neural_nets::optimization::OptimizationFunction< eT >::update().