MachineIntelligenceCore:NeuralNets: src/tests/mnist_simple_mlnn.cpp File Reference
mnist_simple_mlnn.cpp File Reference
#include <logger/Log.hpp>
#include <logger/ConsoleOutput.hpp>
#include <iomanip>
#include <importers/MNISTMatrixImporter.hpp>
#include <encoders/MatrixXfMatrixXfEncoder.hpp>
#include <encoders/UIntMatrixXfEncoder.hpp>
#include <mlnn/BackpropagationNeuralNetwork.hpp>
Functions
int main ()
Function Documentation
int main ()
Definition at line 37 of file mnist_simple_mlnn.cpp.
References batch_size, mic::mlnn::BackpropagationNeuralNetwork< eT >::calculateMeanLoss(), mic::mlnn::MultiLayerNeuralNetwork< eT >::countCorrectPredictions(), mic::mlnn::BackpropagationNeuralNetwork< eT >::forward(), mic::mlnn::MultiLayerNeuralNetwork< eT >::getPredictions(), label_encoder, mnist_encoder, mic::mlnn::MultiLayerNeuralNetwork< eT >::pushLayer(), mic::mlnn::BackpropagationNeuralNetwork< eT >::train(), and mic::mlnn::BackpropagationNeuralNetwork< eT >::verify().