MachineIntelligenceCore:NeuralNets: src/tests/mnist_convnet.cpp File Reference
mnist_convnet.cpp File Reference
#include <logger/Log.hpp>
#include <logger/ConsoleOutput.hpp>
#include <iomanip>
#include <importers/MNISTMatrixImporter.hpp>
#include <encoders/MatrixXfMatrixXfEncoder.hpp>
#include <encoders/UIntMatrixXfEncoder.hpp>
#include <mlnn/BackpropagationNeuralNetwork.hpp>
Functions
int main ()
Function Documentation
int main ()
Definition at line 38 of file mnist_convnet.cpp.
References batch_size, label_encoder, mnist_encoder, mic::mlnn::MultiLayerNeuralNetwork< eT >::pushLayer(), mic::mlnn::MultiLayerNeuralNetwork< eT >::resizeBatch(), mic::mlnn::MultiLayerNeuralNetwork< eT >::save(), mic::mlnn::MultiLayerNeuralNetwork< eT >::setOptimization(), mic::mlnn::BackpropagationNeuralNetwork< eT >::test(), mic::mlnn::BackpropagationNeuralNetwork< eT >::train(), and mic::mlnn::BackpropagationNeuralNetwork< eT >::verify().