MachineIntelligenceCore:NeuralNets: src/tests/mlnn_batch_training_test.cpp File Reference
mlnn_batch_training_test.cpp File Reference
Contains program for testing batch training of a multi-layer neural network.
#include <logger/Log.hpp>
#include <logger/ConsoleOutput.hpp>
#include <iostream>
#include <mlnn/BackpropagationNeuralNetwork.hpp>
#include <encoders/MatrixXfMatrixXfEncoder.hpp>
#include <encoders/UIntMatrixXfEncoder.hpp>
#include <types/Batch.hpp>
Functions
int main ()
Detailed Description
Contains program for testing batch training of a multi-layer neural network.
Copyright (C) tkornuta, IBM Corporation 2015-2019
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Author
tkornut
Date
Feb 17, 2016
Definition in file mlnn_batch_training_test.cpp.
Function Documentation
int main ()
Definition at line 41 of file mlnn_batch_training_test.cpp.
References mic::mlnn::MultiLayerNeuralNetwork< eT >::getPredictions(), label_encoder, mic::mlnn::MultiLayerNeuralNetwork< eT >::pushLayer(), mic::mlnn::MultiLayerNeuralNetwork< eT >::setOptimization(), mic::mlnn::BackpropagationNeuralNetwork< eT >::test(), and mic::mlnn::BackpropagationNeuralNetwork< eT >::train().